Added documentation for signing and pushing stable RPMs
radiant-maxar/geoint-apps pull request #11
Opened 2022-07-26 20:36 UTC by hummeltech

2023-01-25 16:59 UTC, BuechnerGIS approved these changes
:rocket:

2023-01-25 17:24 UTC, jbronn requested changes
As-is I'm -1.  From what I can tell, these scripts are signing *every* RPM that's built, even if their versions aren't changed.  I don't like our build artifacts changing each time we sign one release, in addition to the havoc this will wreak on Docker's BuildKit caching.

2023-01-25 17:34 UTC, hummeltech commented on scripts/push_stable_rpms_from_zip.sh
> +  bash -c "rsync --archive --ignore-existing --verbose EXTRACTED_RPMS/*/*.rpm ${REPO_PREFIX}"
@jbronn Yep, you must have missed this line, although all RPMs are indeed being signed, only the "new" ones are copied over.

2023-01-26 17:32 UTC, jbronn commented on scripts/push_stable_rpms_from_zip.sh
> +  bash -c "rsync --archive --ignore-existing --verbose EXTRACTED_RPMS/*/*.rpm ${REPO_PREFIX}"
Yes, I did miss this line and addresses my concerns.

2023-01-26 17:32 UTC, jbronn approved these changes
LGTM

2023-01-26 18:30 UTC, merged